spring:
  application:
    name: eureka-client
server:
  port: 1002

feign:
  hystrix:
    enabled: true
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka
    enabled: true
